Introduction to Pandas
Pandas is used for Python Data Analytics. It performs the operation of Data Cleaning and Transformation.

It is used for representing the data in tabular form.

It is far more efficient than Excel.

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = np.array([100,200,300,400,500])
print(data)

ds = pd.Series(data)

[100 200 300 400 500]

In [4]:
print(ds)

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [5]:
cities = np.array(['Solapur','Pune','Chennai','Mumbai','Hyderabad','Bengaluru'])
print(cities)

['Solapur' 'Pune' 'Chennai' 'Mumbai' 'Hyderabad' 'Bengaluru']

In [6]:
cs = pd.Series(cities)
print(cs)

0      Solapur
1         Pune
2      Chennai
3       Mumbai
4    Hyderabad
5    Bengaluru
dtype: object

In [19]:
students = {
    'name':['Nihal','Gufran','Ahmed','Faiz','Sadik','Onkar'],
    'city':['Solapur','Mumbai','Lahor','Chennai','Kabul','Delhi'],
    'mark':[75,88,94,69,87,64]
}
print(students)

{'name': ['Nihal', 'Gufran', 'Ahmed', 'Faiz', 'Sadik', 'Onkar'], 'city': ['Solapur', 'Mumbai', 'Lahor', 'Chennai', 'Kabul', 'Delhi'], 'mark': [75, 88, 94, 69, 87, 64]}

In [20]:
df = pd.DataFrame(students)
print(df)

     name     city  mark
0   Nihal  Solapur    75
1  Gufran   Mumbai    88
2   Ahmed    Lahor    94
3    Faiz  Chennai    69
4   Sadik    Kabul    87
5   Onkar    Delhi    64

In [10]:
df

     name     city
0   Nihal  Solapur
1  Gufran   Mumbai
2   Ahmed    Lahor
3    Faiz  Chennai
4   Sadik    Kabul

'Solapur'

Reading the data from a CSV file using read_csv method

In [23]:
df = pd.read_csv('demo.csv')
df

     name     city  mark
0   Nihal  Solapur    75
1  Gufran   Mumbai    88
2   Ahmed    Lahor    94
3    Faiz  Chennai    69
4   Sadik    Kabul    87
5   Onkar    Delhi    64