Assignment on Employees Data

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('empdata.csv')
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance       NaN  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

Data Cleaning - Replace NaN value from Salary column with Median of Finance Department Salaries

In [4]:
df_salary_na = df['Salary'].isna()
df_salary_na

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: Salary, dtype: bool

In [5]:
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance       NaN  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

In [6]:
df_fin= df[df['Dept']=='Finance']
df_fin

        ID   Name     Dept    Salary        Date
1   EMP002    Bob  Finance  117969.0  2018-06-06
3   EMP004  David  Finance       NaN  2019-04-15
4   EMP005    Eva  Finance   78693.0  2019-09-18
9   EMP010   Jack  Finance  109150.0  2021-11-08
12  EMP013  Molly  Finance  117435.0  2023-02-21

In [7]:
med = df_fin['Salary'].median()
med

113292.5

In [8]:
df['Salary']=df['Salary'].fillna(med)
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance  113292.5  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

Data Cleaning - Replacing NaN department by 'Marketing'

In [9]:
df.iloc[7,2] = 'Marketing'
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance  113292.5  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah    Marketing   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

Filtering: Filter the DataFrame to show only employees who earn more than 100,000 and work in "Sales" or "Engineering".

In [10]:
(df['Salary']>100000)

0      True
1      True
2     False
3      True
4     False
5      True
6     False
7     False
8     False
9      True
10     True
11    False
12     True
13     True
14     True
Name: Salary, dtype: bool

In [11]:
df['Dept'].isin(['Sales','Engineering'])

0      True
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14     True
Name: Dept, dtype: bool

In [12]:
df[(df['Salary']>100000) & (df['Dept'].isin(['Sales','Engineering']))].sort_values(['Dept','Name'])

        ID    Name         Dept    Salary        Date
5   EMP006   Frank  Engineering  121932.0  2020-02-22
13  EMP014  Nathan  Engineering  106886.0  2023-07-27
0   EMP001   Alice        Sales  114925.0  2018-01-01
10  EMP011   Kevin        Sales  115725.0  2022-04-14
14  EMP015  Oliver        Sales  116803.0  2023-12-31

Aggregation: Calculate the average salary and total employee count for each unique department.

In [13]:
df_x=df.groupby('Dept')
df_x['Salary'].mean()

Dept
Engineering    114409.000000
Finance        107307.900000
Marketing       67584.000000
Sales          115817.666667
Name: Salary, dtype: float64

In [14]:
df_x['ID'].count()

Dept
Engineering    2
Finance        5
Marketing      5
Sales          3
Name: ID, dtype: int64

In [15]:
df_result = pd.DataFrame({
    'Avg Salary':df_x['Salary'].mean(),
    'count':df_x['ID'].count()
})

df_result

                Avg Salary  count
Dept
Engineering  114409.000000      2
Finance      107307.900000      5
Marketing     67584.000000      5
Sales        115817.666667      3

Datetime Handling: Convert the Join_Date column to actual datetime objects and filter out anyone who joined after January 1st, 2021.

In [16]:
df[df['Date']>='2021-01-01'].sort_values('Date',ascending=False)

        ID    Name         Dept    Salary        Date
14  EMP015  Oliver        Sales  116803.0  2023-12-31
13  EMP014  Nathan  Engineering  106886.0  2023-07-27
12  EMP013   Molly      Finance  117435.0  2023-02-21
11  EMP012   Laura    Marketing   85773.0  2022-09-17
10  EMP011   Kevin        Sales  115725.0  2022-04-14
9   EMP010    Jack      Finance  109150.0  2021-11-08
8   EMP009    Ivan    Marketing   52747.0  2021-06-05

Feature Engineering: Create a new column named Years_of_Service based on how many years they have been at the company relative to today.

In [17]:
today = pd.to_datetime('today')

In [18]:
df['Date']=pd.to_datetime(df['Date'])

In [19]:
# 2. Calculate the total difference in days
total_days = (today - df['Date']).dt.days
total_years = total_days//365
total_months = (total_days%365)//30.44    
df['Years_of_Service'] = (total_years.astype(int).astype(str)+' Yr '+total_months.astype(int).astype(str)+' Mt')
df

        ID     Name         Dept    Salary       Date Years_of_Service
0   EMP001    Alice        Sales  114925.0 2018-01-01        8 Yr 5 Mt
1   EMP002      Bob      Finance  117969.0 2018-06-06        8 Yr 0 Mt
2   EMP003  Charlie    Marketing   55311.0 2018-11-09        7 Yr 7 Mt
3   EMP004    David      Finance  113292.5 2019-04-15        7 Yr 2 Mt
4   EMP005      Eva      Finance   78693.0 2019-09-18        6 Yr 9 Mt
5   EMP006    Frank  Engineering  121932.0 2020-02-22        6 Yr 4 Mt
6   EMP007    Grace    Marketing   75658.0 2020-07-27       5 Yr 10 Mt
7   EMP008   Hannah    Marketing   68431.0 2020-12-31        5 Yr 5 Mt
8   EMP009     Ivan    Marketing   52747.0 2021-06-05        5 Yr 0 Mt
9   EMP010     Jack      Finance  109150.0 2021-11-08        4 Yr 7 Mt
10  EMP011    Kevin        Sales  115725.0 2022-04-14        4 Yr 2 Mt
11  EMP012    Laura    Marketing   85773.0 2022-09-17        3 Yr 9 Mt
12  EMP013    Molly      Finance  117435.0 2023-02-21        3 Yr 4 Mt
13  EMP014   Nathan  Engineering  106886.0 2023-07-27       2 Yr 10 Mt
14  EMP015   Oliver        Sales  116803.0 2023-12-31        2 Yr 5 Mt

Multi-Condition Filtering & Indexing - 
Extract a new DataFrame containing only employees from Sales or Finance who have a salary above 110,000. Reset the index of this new DataFrame so it starts from 0

In [20]:
df[df['Salary']>110000]

        ID    Name         Dept    Salary       Date Years_of_Service
0   EMP001   Alice        Sales  114925.0 2018-01-01        8 Yr 5 Mt
1   EMP002     Bob      Finance  117969.0 2018-06-06        8 Yr 0 Mt
3   EMP004   David      Finance  113292.5 2019-04-15        7 Yr 2 Mt
5   EMP006   Frank  Engineering  121932.0 2020-02-22        6 Yr 4 Mt
10  EMP011   Kevin        Sales  115725.0 2022-04-14        4 Yr 2 Mt
12  EMP013   Molly      Finance  117435.0 2023-02-21        3 Yr 4 Mt
14  EMP015  Oliver        Sales  116803.0 2023-12-31        2 Yr 5 Mt

In [21]:
df[df['Dept'].isin(['Sales','Finance'])]

        ID    Name     Dept    Salary       Date Years_of_Service
0   EMP001   Alice    Sales  114925.0 2018-01-01        8 Yr 5 Mt
1   EMP002     Bob  Finance  117969.0 2018-06-06        8 Yr 0 Mt
3   EMP004   David  Finance  113292.5 2019-04-15        7 Yr 2 Mt
4   EMP005     Eva  Finance   78693.0 2019-09-18        6 Yr 9 Mt
9   EMP010    Jack  Finance  109150.0 2021-11-08        4 Yr 7 Mt
10  EMP011   Kevin    Sales  115725.0 2022-04-14        4 Yr 2 Mt
12  EMP013   Molly  Finance  117435.0 2023-02-21        3 Yr 4 Mt
14  EMP015  Oliver    Sales  116803.0 2023-12-31        2 Yr 5 Mt

In [22]:
new_df = df[(df['Salary']>110000) & (df['Dept'].isin(['Sales','Finance']))]
new_df

        ID    Name     Dept    Salary       Date Years_of_Service
0   EMP001   Alice    Sales  114925.0 2018-01-01        8 Yr 5 Mt
1   EMP002     Bob  Finance  117969.0 2018-06-06        8 Yr 0 Mt
3   EMP004   David  Finance  113292.5 2019-04-15        7 Yr 2 Mt
10  EMP011   Kevin    Sales  115725.0 2022-04-14        4 Yr 2 Mt
12  EMP013   Molly  Finance  117435.0 2023-02-21        3 Yr 4 Mt
14  EMP015  Oliver    Sales  116803.0 2023-12-31        2 Yr 5 Mt

In [23]:
new_df.reset_index(0,drop=True)

       ID    Name     Dept    Salary       Date Years_of_Service
0  EMP001   Alice    Sales  114925.0 2018-01-01        8 Yr 5 Mt
1  EMP002     Bob  Finance  117969.0 2018-06-06        8 Yr 0 Mt
2  EMP004   David  Finance  113292.5 2019-04-15        7 Yr 2 Mt
3  EMP011   Kevin    Sales  115725.0 2022-04-14        4 Yr 2 Mt
4  EMP013   Molly  Finance  117435.0 2023-02-21        3 Yr 4 Mt
5  EMP015  Oliver    Sales  116803.0 2023-12-31        2 Yr 5 Mt

Ranking - Create a new column called Salary_Rank that ranks employees from highest salary (Rank 1) to lowest salary (Rank 14, ignoring the NaN value). Use the .rank() method.

In [24]:
df.sort_values('Salary')

        ID     Name         Dept    Salary       Date Years_of_Service
8   EMP009     Ivan    Marketing   52747.0 2021-06-05        5 Yr 0 Mt
2   EMP003  Charlie    Marketing   55311.0 2018-11-09        7 Yr 7 Mt
7   EMP008   Hannah    Marketing   68431.0 2020-12-31        5 Yr 5 Mt
6   EMP007    Grace    Marketing   75658.0 2020-07-27       5 Yr 10 Mt
4   EMP005      Eva      Finance   78693.0 2019-09-18        6 Yr 9 Mt
11  EMP012    Laura    Marketing   85773.0 2022-09-17        3 Yr 9 Mt
13  EMP014   Nathan  Engineering  106886.0 2023-07-27       2 Yr 10 Mt
9   EMP010     Jack      Finance  109150.0 2021-11-08        4 Yr 7 Mt
3   EMP004    David      Finance  113292.5 2019-04-15        7 Yr 2 Mt
0   EMP001    Alice        Sales  114925.0 2018-01-01        8 Yr 5 Mt
10  EMP011    Kevin        Sales  115725.0 2022-04-14        4 Yr 2 Mt
14  EMP015   Oliver        Sales  116803.0 2023-12-31        2 Yr 5 Mt
12  EMP013    Molly      Finance  117435.0 2023-02-21        3 Yr 4 Mt
1   EMP002      Bob      Finance  117969.0 2018-06-06        8 Yr 0 Mt
5   EMP006    Frank  Engineering  121932.0 2020-02-22        6 Yr 4 Mt

In [25]:
df['salary_rank']=df['Salary'].rank(ascending=False)

In [26]:
df

,ID,Name,Dept,Salary,Date,Years_of_Service,salary_rank
0,EMP001,Alice,Sales,114925.0,2018-01-01,8 Yr 5 Mt,6.0
1,EMP002,Bob,Finance,117969.0,2018-06-06,8 Yr 0 Mt,2.0
2,EMP003,Charlie,Marketing,55311.0,2018-11-09,7 Yr 7 Mt,14.0
3,EMP004,David,Finance,113292.5,2019-04-15,7 Yr 2 Mt,7.0
4,EMP005,Eva,Finance,78693.0,2019-09-18,6 Yr 9 Mt,11.0
5,EMP006,Frank,Engineering,121932.0,2020-02-22,6 Yr 4 Mt,1.0
6,EMP007,Grace,Marketing,75658.0,2020-07-27,5 Yr 10 Mt,12.0
7,EMP008,Hannah,Marketing,68431.0,2020-12-31,5 Yr 5 Mt,13.0
8,EMP009,Ivan,Marketing,52747.0,2021-06-05,5 Yr 0 Mt,15.0
9,EMP010,Jack,Finance,109150.0,2021-11-08,4 Yr 7 Mt,8.0
10,EMP011,Kevin,Sales,115725.0,2022-04-14,4 Yr 2 Mt,5.0
11,EMP012,Laura,Marketing,85773.0,2022-09-17,3 Yr 9 Mt,10.0
12,EMP013,Molly,Finance,117435.0,2023-02-21,3 Yr 4 Mt,3.0
13,EMP014,Nathan,Engineering,106886.0,2023-07-27,2 Yr 10 Mt,9.0
14,EMP015,Oliver,Sales,116803.0,2023-12-31,2 Yr 5 Mt,4.0

In [27]:
deptwise_budget=df_x['Salary'].sum()
deptwise_budget

Dept
Engineering    228818.0
Finance        536539.5
Marketing      337920.0
Sales          347453.0
Name: Salary, dtype: float64

Conditional Column Creation (Experience Tiers)Use pd.cut() or a custom function to create an Experience_Level column based on your previous Years_of_Service calculation:
    Less than 4 years -> "Junior" 
    4 to 7 years -> "Mid-Level"
    Over 7 years -> "Senior"

In [28]:
df

,ID,Name,Dept,Salary,Date,Years_of_Service,salary_rank
0,EMP001,Alice,Sales,114925.0,2018-01-01,8 Yr 5 Mt,6.0
1,EMP002,Bob,Finance,117969.0,2018-06-06,8 Yr 0 Mt,2.0
2,EMP003,Charlie,Marketing,55311.0,2018-11-09,7 Yr 7 Mt,14.0
3,EMP004,David,Finance,113292.5,2019-04-15,7 Yr 2 Mt,7.0
4,EMP005,Eva,Finance,78693.0,2019-09-18,6 Yr 9 Mt,11.0
5,EMP006,Frank,Engineering,121932.0,2020-02-22,6 Yr 4 Mt,1.0
6,EMP007,Grace,Marketing,75658.0,2020-07-27,5 Yr 10 Mt,12.0
7,EMP008,Hannah,Marketing,68431.0,2020-12-31,5 Yr 5 Mt,13.0
8,EMP009,Ivan,Marketing,52747.0,2021-06-05,5 Yr 0 Mt,15.0
9,EMP010,Jack,Finance,109150.0,2021-11-08,4 Yr 7 Mt,8.0
10,EMP011,Kevin,Sales,115725.0,2022-04-14,4 Yr 2 Mt,5.0
11,EMP012,Laura,Marketing,85773.0,2022-09-17,3 Yr 9 Mt,10.0
12,EMP013,Molly,Finance,117435.0,2023-02-21,3 Yr 4 Mt,3.0
13,EMP014,Nathan,Engineering,106886.0,2023-07-27,2 Yr 10 Mt,9.0
14,EMP015,Oliver,Sales,116803.0,2023-12-31,2 Yr 5 Mt,4.0

In [49]:
years=total_days/365

In [50]:
df['experience_level']=pd.cut(years,bins=[0,4,7,15],labels=['Jr','Mid','Sr'])
df

,ID,Name,Dept,Salary,Date,Years_of_Service,salary_rank,experience_level
0,EMP001,Alice,Sales,114925.0,2018-01-01,8 Yr 5 Mt,6.0,Sr
1,EMP002,Bob,Finance,117969.0,2018-06-06,8 Yr 0 Mt,2.0,Sr
2,EMP003,Charlie,Marketing,55311.0,2018-11-09,7 Yr 7 Mt,14.0,Sr
3,EMP004,David,Finance,113292.5,2019-04-15,7 Yr 2 Mt,7.0,Sr
4,EMP005,Eva,Finance,78693.0,2019-09-18,6 Yr 9 Mt,11.0,Mid
5,EMP006,Frank,Engineering,121932.0,2020-02-22,6 Yr 4 Mt,1.0,Mid
6,EMP007,Grace,Marketing,75658.0,2020-07-27,5 Yr 10 Mt,12.0,Mid
7,EMP008,Hannah,Marketing,68431.0,2020-12-31,5 Yr 5 Mt,13.0,Mid
8,EMP009,Ivan,Marketing,52747.0,2021-06-05,5 Yr 0 Mt,15.0,Mid
9,EMP010,Jack,Finance,109150.0,2021-11-08,4 Yr 7 Mt,8.0,Mid
10,EMP011,Kevin,Sales,115725.0,2022-04-14,4 Yr 2 Mt,5.0,Mid
11,EMP012,Laura,Marketing,85773.0,2022-09-17,3 Yr 9 Mt,10.0,Jr
12,EMP013,Molly,Finance,117435.0,2023-02-21,3 Yr 4 Mt,3.0,Jr
13,EMP014,Nathan,Engineering,106886.0,2023-07-27,2 Yr 10 Mt,9.0,Jr
14,EMP015,Oliver,Sales,116803.0,2023-12-31,2 Yr 5 Mt,4.0,Jr

Multi-Level Grouping & Aggregation - 
Assume you have created the Experience_Level column (Junior, Mid-Level, Senior) using pd.cut(). Group the dataset by both Department and Experience_Level, then calculate the average salary for each combination.

In [57]:
df_y=df.groupby(['Dept','experience_level'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_8424\1638024100.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_y=df.groupby(['Dept','experience_level'])

In [59]:
df_y['Salary'].mean().fillna(0)

Dept         experience_level
Engineering  Jr                  106886.00
             Mid                 121932.00
             Sr                       0.00
Finance      Jr                  117435.00
             Mid                  93921.50
             Sr                  115630.75
Marketing    Jr                   85773.00
             Mid                  65612.00
             Sr                   55311.00
Sales        Jr                  116803.00
             Mid                 115725.00
             Sr                  114925.00
Name: Salary, dtype: float64

Give a 10% raise to all employees in the "Marketing" department who have a salary below 60,000. Modify the Salary column directly using .loc.

In [80]:
filter = (df['Dept']=='Marketing') & (df['Salary']<60000)
salary = df.loc[filter]['Salary']
salary += (salary * 0.1)
salary

df.loc[filter,'Salary']= salary
df

,ID,Name,Dept,Salary,Date,Years_of_Service,salary_rank,experience_level
0,EMP001,Alice,Sales,114925.0,2018-01-01,8 Yr 5 Mt,6.0,Sr
1,EMP002,Bob,Finance,117969.0,2018-06-06,8 Yr 0 Mt,2.0,Sr
2,EMP003,Charlie,Marketing,608421.0,2018-11-09,7 Yr 7 Mt,14.0,Sr
3,EMP004,David,Finance,113292.5,2019-04-15,7 Yr 2 Mt,7.0,Sr
4,EMP005,Eva,Finance,78693.0,2019-09-18,6 Yr 9 Mt,11.0,Mid
5,EMP006,Frank,Engineering,121932.0,2020-02-22,6 Yr 4 Mt,1.0,Mid
6,EMP007,Grace,Marketing,75658.0,2020-07-27,5 Yr 10 Mt,12.0,Mid
7,EMP008,Hannah,Marketing,68431.0,2020-12-31,5 Yr 5 Mt,13.0,Mid
8,EMP009,Ivan,Marketing,580217.0,2021-06-05,5 Yr 0 Mt,15.0,Mid
9,EMP010,Jack,Finance,109150.0,2021-11-08,4 Yr 7 Mt,8.0,Mid
10,EMP011,Kevin,Sales,115725.0,2022-04-14,4 Yr 2 Mt,5.0,Mid
11,EMP012,Laura,Marketing,85773.0,2022-09-17,3 Yr 9 Mt,10.0,Jr
12,EMP013,Molly,Finance,117435.0,2023-02-21,3 Yr 4 Mt,3.0,Jr
13,EMP014,Nathan,Engineering,106886.0,2023-07-27,2 Yr 10 Mt,9.0,Jr
14,EMP015,Oliver,Sales,116803.0,2023-12-31,2 Yr 5 Mt,4.0,Jr