In [1]:
import pandas as pd

In [19]:
df = pd.read_csv('course_data.csv')
df

    Sr. No                           Course       Domain  Duration
0        1           Full Stack Development         Java  6 Months
1        2           Full Stack Development       Python  6 Months
2        3                  Ethical Hacking      General  3 Months
3        4           Full Stack Development      Dot Net  6 Months
4        5           Full Stack Development   MEAN Stack  6 Months
5        6           Full Stack Development   MERN Stack  6 Months
6        7  Data Science & Machine Learning       Python  6 Months
7        8                   Data Analytics       Python  4 Months
8        9                  Web Development  HTML/CSS/JS  3 Months
9       10          Android App Development       Kotlin  3 Months
10      11              iOS App Development        Swift  3 Months
11      11              iOS App Development        Swift  3 Months
12      12                  Cloud Computing          AWS  3 Months
13      13                           DevOps        Tools  3 Months
14      14                    Cybersecurity      General  3 Months
15      15                     UI/UX Design        Figma  2 Months
16      16                Digital Marketing      General  2 Months
17      17          Artificial Intelligence       Python  4 Months
18      18           Full Stack Development          PHP  6 Months
19      18           Full Stack Development          PHP  6 Months
20      18           Full Stack Development          PHP  6 Months

In [3]:
def fee_calculator(duration):
    monthly_fee = 2000
    return monthly_fee * duration

In [47]:
df['num_months']=df['Duration'].str[0]
df['num_months']=df['num_months'].astype(int)

In [42]:
df

    Sr. No                           Course       Domain  Duration num_months
0        1           Full Stack Development         Java  6 Months          6
1        2           Full Stack Development       Python  6 Months          6
2        3                  Ethical Hacking      General  3 Months          3
3        4           Full Stack Development      Dot Net  6 Months          6
4        5           Full Stack Development   MEAN Stack  6 Months          6
5        6           Full Stack Development   MERN Stack  6 Months          6
6        7  Data Science & Machine Learning       Python  6 Months          6
7        8                   Data Analytics       Python  4 Months          4
8        9                  Web Development  HTML/CSS/JS  3 Months          3
9       10          Android App Development       Kotlin  3 Months          3
10      11              iOS App Development        Swift  3 Months          3
11      11              iOS App Development        Swift  3 Months          3
12      12                  Cloud Computing          AWS  3 Months          3
13      13                           DevOps        Tools  3 Months          3
14      14                    Cybersecurity      General  3 Months          3
15      15                     UI/UX Design        Figma  2 Months          2
16      16                Digital Marketing      General  2 Months          2
17      17          Artificial Intelligence       Python  4 Months          4
18      18           Full Stack Development          PHP  6 Months          6
19      18           Full Stack Development          PHP  6 Months          6
20      18           Full Stack Development          PHP  6 Months          6

In [48]:
df['total_fee'] = df['num_months'].apply(fee_calculator)
df['total_fee']

0     12000
1     12000
2      6000
3     12000
4     12000
5     12000
6     12000
7      8000
8      6000
9      6000
10     6000
11     6000
12     6000
13     6000
14     6000
15     4000
16     4000
17     8000
18    12000
19    12000
20    12000
Name: total_fee, dtype: int64

In [49]:
df

,Sr. No,Course,Domain,Duration,num_months,total_fee
0,1,Full Stack Development,Java,6 Months,6,12000
1,2,Full Stack Development,Python,6 Months,6,12000
2,3,Ethical Hacking,General,3 Months,3,6000
3,4,Full Stack Development,Dot Net,6 Months,6,12000
4,5,Full Stack Development,MEAN Stack,6 Months,6,12000
5,6,Full Stack Development,MERN Stack,6 Months,6,12000
6,7,Data Science & Machine Learning,Python,6 Months,6,12000
7,8,Data Analytics,Python,4 Months,4,8000
8,9,Web Development,HTML/CSS/JS,3 Months,3,6000
9,10,Android App Development,Kotlin,3 Months,3,6000
10,11,iOS App Development,Swift,3 Months,3,6000
11,11,iOS App Development,Swift,3 Months,3,6000
12,12,Cloud Computing,AWS,3 Months,3,6000
13,13,DevOps,Tools,3 Months,3,6000
14,14,Cybersecurity,General,3 Months,3,6000
15,15,UI/UX Design,Figma,2 Months,2,4000
16,16,Digital Marketing,General,2 Months,2,4000
17,17,Artificial Intelligence,Python,4 Months,4,8000
18,18,Full Stack Development,PHP,6 Months,6,12000
19,18,Full Stack Development,PHP,6 Months,6,12000
20,18,Full Stack Development,PHP,6 Months,6,12000