In [1]:
import pandas as pd

In [8]:
dataset = {
    'dept':['IT','Sales','IT','Marketing','Sales','Purchase','Sales','HR','HR','Marketing'],
    'salary':[55000,25000,80000,20000,45000,30000,40000,45000,45000,20000]
}

In [9]:
df = pd.DataFrame(dataset)
df

        dept  salary
0         IT   55000
1      Sales   25000
2         IT   80000
3  Marketing   20000
4      Sales   45000
5   Purchase   30000
6      Sales   40000
7         HR   45000
8         HR   45000
9  Marketing   20000

In [10]:
dept_df=df.groupby('dept')
dept_df

In [18]:
total_salary=dept_df.sum()
total_salary

           salary
dept
HR          90000
IT         135000
Marketing   40000
Purchase    30000
Sales      110000

In [12]:
dept_df.mean()

                 salary
dept
HR         45000.000000
IT         67500.000000
Marketing  20000.000000
Purchase   30000.000000
Sales      36666.666667

In [13]:
dept_df.count()

           salary
dept
HR              2
IT              2
Marketing       2
Purchase        1
Sales           3

In [14]:
dept_df.min()

           salary
dept
HR          45000
IT          55000
Marketing   20000
Purchase    30000
Sales       25000

In [15]:
dept_df.max()

           salary
dept
HR          45000
IT          80000
Marketing   20000
Purchase    30000
Sales       45000

In [25]:
sorted_Salary=total_salary.sort_values('salary',ascending=False)
sorted_Salary

           salary
dept
IT         135000
Sales      110000
HR          90000
Marketing   40000
Purchase    30000

In [28]:
top_two = total_salary['salary']>90000
print(top_two)
total_salary[top_two]

dept
HR           False
IT            True
Marketing    False
Purchase     False
Sales         True
Name: salary, dtype: bool

       salary
dept
IT     135000
Sales  110000