Assignment on Employees Data

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('empdata.csv')
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance       NaN  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

In [ ]:
df_salary_na = df['Salary'].isna()
df_salary_na

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: Salary, dtype: bool

In [12]:
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance       NaN  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

In [22]:
df_fin= df[df['Dept']=='Finance']
df_fin

        ID   Name     Dept    Salary        Date
1   EMP002    Bob  Finance  117969.0  2018-06-06
3   EMP004  David  Finance       NaN  2019-04-15
4   EMP005    Eva  Finance   78693.0  2019-09-18
9   EMP010   Jack  Finance  109150.0  2021-11-08
12  EMP013  Molly  Finance  117435.0  2023-02-21

In [23]:
med = df_fin['Salary'].median()
med

113292.5

In [26]:
df['Salary']=df['Salary'].fillna(med)
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance  113292.5  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31