Pandas - Analyzing the Dataframes

In [45]:
import pandas as pd

In [46]:
data = pd.read_csv('course_data.csv')

In [47]:
data

    Sr. No                           Course       Domain  Duration
0        1           Full Stack Development         Java  6 Months
1        2           Full Stack Development       Python  6 Months
2        3                  Ethical Hacking      General  3 Months
3        4           Full Stack Development      Dot Net  6 Months
4        5           Full Stack Development   MEAN Stack  6 Months
5        6           Full Stack Development   MERN Stack  6 Months
6        7  Data Science & Machine Learning       Python  6 Months
7        8                   Data Analytics       Python  4 Months
8        9                  Web Development  HTML/CSS/JS  3 Months
9       10          Android App Development       Kotlin  3 Months
10      11              iOS App Development        Swift  3 Months
11      12                  Cloud Computing          AWS  3 Months
12      13                           DevOps        Tools  3 Months
13      14                    Cybersecurity      General  3 Months
14      15                     UI/UX Design        Figma  2 Months
15      16                Digital Marketing      General  2 Months
16      17          Artificial Intelligence       Python  4 Months
17      18           Full Stack Development          PHP  6 Months

In [48]:
data.head()

   Sr. No                  Course      Domain  Duration
0       1  Full Stack Development        Java  6 Months
1       2  Full Stack Development      Python  6 Months
2       3         Ethical Hacking     General  3 Months
3       4  Full Stack Development     Dot Net  6 Months
4       5  Full Stack Development  MEAN Stack  6 Months

In [49]:
data.head()

   Sr. No                  Course      Domain  Duration
0       1  Full Stack Development        Java  6 Months
1       2  Full Stack Development      Python  6 Months
2       3         Ethical Hacking     General  3 Months
3       4  Full Stack Development     Dot Net  6 Months
4       5  Full Stack Development  MEAN Stack  6 Months

In [50]:
data.tail(1)

    Sr. No                  Course Domain  Duration
17      18  Full Stack Development    PHP  6 Months

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sr. No    18 non-null     int64
 1   Course    18 non-null     object
 2   Domain    18 non-null     object
 3   Duration  18 non-null     object
dtypes: int64(1), object(3)
memory usage: 708.0+ bytes

In [52]:
print(data.iloc[3,3])

6 Months

In [55]:
data.iloc[0:6,1:4]

                   Course      Domain  Duration
0  Full Stack Development        Java  6 Months
1  Full Stack Development      Python  6 Months
2         Ethical Hacking     General  3 Months
3  Full Stack Development     Dot Net  6 Months
4  Full Stack Development  MEAN Stack  6 Months
5  Full Stack Development  MERN Stack  6 Months

In [ ]:
fsd = data[data['Course'] == 'Full Stack Development']
fsd.iloc[0:,1:4]

                        Course                  Domain                Duration
0       Full Stack Development                    Java                6 Months
1       Full Stack Development                  Python                6 Months
3       Full Stack Development                 Dot Net                6 Months
4       Full Stack Development              MEAN Stack                6 Months
5       Full Stack Development              MERN Stack                6 Months
17      Full Stack Development                     PHP                6 Months
Course  Full Stack Development  Full Stack Development  Full Stack Development

In [86]:
fsd.loc[:,['Domain','Course','Duration']]

                        Domain                  Course                Duration
0                         Java  Full Stack Development                6 Months
1                       Python  Full Stack Development                6 Months
3                      Dot Net  Full Stack Development                6 Months
4                   MEAN Stack  Full Stack Development                6 Months
5                   MERN Stack  Full Stack Development                6 Months
17                         PHP  Full Stack Development                6 Months
Course  Full Stack Development  Full Stack Development  Full Stack Development