Working with DataFrame.

In [2]:
import pandas as pd

In [3]:
student_marks = {
    'c_marks' : [78,75,98,95,96],
    'cpp_marks' : [88,86,79,65,50],
    'java_marks': [77,81,96,93,92]
}

In [4]:
marks_table = pd.DataFrame(student_marks)
print(marks_table)

   c_marks  cpp_marks  java_marks
0       78         88          77
1       75         86          81
2       98         79          96
3       95         65          93
4       96         50          92

In [5]:
marks_table

   c_marks  cpp_marks  java_marks
0       78         88          77
1       75         86          81
2       98         79          96
3       95         65          93
4       96         50          92

In [68]:
student_marks = {
    'names' : ['Stud1','Stud2','Stud3','Stud3','Stud5','Stud3'],
    'c_marks' : [78,75,98,95,96,88],
    'cpp_marks' : [88,86,79,65,50,67],
    'java_marks': [77,81,96,93,92,75]
}

In [69]:
marks_table = pd.DataFrame(student_marks)
print(marks_table)

   names  c_marks  cpp_marks  java_marks
0  Stud1       78         88          77
1  Stud2       75         86          81
2  Stud3       98         79          96
3  Stud3       95         65          93
4  Stud5       96         50          92
5  Stud3       88         67          75

In [29]:
print(marks_table.iloc[2,2])

79

In [30]:
row = marks_table.iloc[4,1:4]
print('Total marks - ',row.sum())
print(f'Percentage - {row.mean():.2f}')

Total marks -  238
Percentage - 79.33

In [70]:
marks_table = pd.DataFrame(student_marks)
marks_table.set_index('names',inplace=True)
print(marks_table)

       c_marks  cpp_marks  java_marks
names
Stud1       78         88          77
Stud2       75         86          81
Stud3       98         79          96
Stud3       95         65          93
Stud5       96         50          92
Stud3       88         67          75

In [32]:
print(marks_table.loc['Stud5'])

c_marks       96
cpp_marks     50
java_marks    92
Name: Stud5, dtype: int64

In [71]:
print(marks_table.loc['Stud3','cpp_marks'])

names
Stud3    79
Stud3    65
Stud3    67
Name: cpp_marks, dtype: int64

In [41]:
print(marks_table.iloc[0:3])

       c_marks  cpp_marks  java_marks
names
Stud1       78         88          77
Stud2       75         86          81
Stud3       98         79          96

In [57]:
print(marks_table.iloc[[0,3,4],[0,1]])

       c_marks  cpp_marks
names
Stud1       78         88
Stud3       95         65
Stud5       96         50

In [58]:
print(marks_table.sum(axis=0))

c_marks       530
cpp_marks     435
java_marks    514
dtype: int64

In [62]:
print(marks_table.iloc[0:,0])

names
Stud1    78
Stud2    75
Stud3    98
Stud3    95
Stud5    96
Stud3    88
Name: c_marks, dtype: int64

In [63]:
print(marks_table.sum(axis=1))

names
Stud1    243
Stud2    242
Stud3    273
Stud3    253
Stud5    238
Stud3    230
dtype: int64

In [72]:
total = marks_table.sum(axis=1)
percentage = marks_table.mean(axis=1)

In [77]:
marks_table['total'] = total
marks_table['percentage'] = percentage.round(2)
marks_table

       c_marks  cpp_marks  java_marks  total  percentage
names
Stud1       78         88          77    243       81.00
Stud2       75         86          81    242       80.67
Stud3       98         79          96    273       91.00
Stud3       95         65          93    253       84.33
Stud5       96         50          92    238       79.33
Stud3       88         67          75    230       76.67