In [1]:
import pandas as pd

In [15]:
data = {
    'student_name':['Ahmed','Nihal','Onkar','Faiz','Madiha','Tanzila','Gufran'],
    'student_marks':[85,91,None,79,None,81,None]
}

In [25]:
df = pd.DataFrame(data)
df

  student_name  student_marks
0        Ahmed           85.0
1        Nihal           91.0
2        Onkar            NaN
3         Faiz           79.0
4       Madiha            NaN
5      Tanzila           81.0
6       Gufran            NaN

In [17]:
df_null = df.isnull()
df_null

   student_name  student_marks
0         False          False
1         False          False
2         False           True
3         False          False
4         False           True
5         False          False
6         False           True

In [18]:
df_null.sum()

student_name     0
student_marks    3
dtype: int64

In [13]:
df['student_marks']=df['student_marks'].fillna(0)
df

  student_name  student_marks
0        Ahmed           85.0
1        Nihal           91.0
2        Onkar            0.0
3         Faiz           79.0
4       Madiha            0.0
5      Tanzila           81.0
6       Gufran            0.0

In [35]:
df_updated=df.dropna(axis=0)
df_updated

  student_name  student_marks
0        Ahmed           85.0
1        Nihal           91.0
3         Faiz           79.0
5      Tanzila           81.0

In [36]:
df_updated

  student_name  student_marks
0        Ahmed           85.0
1        Nihal           91.0
3         Faiz           79.0
5      Tanzila           81.0