Assignment on Employees Data

In [69]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('empdata.csv')
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance       NaN  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

Data Cleaning - Replace NaN value from Salary column with Median of Finance Department Salaries

In [3]:
df_salary_na = df['Salary'].isna()
df_salary_na

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: Salary, dtype: bool

In [4]:
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance       NaN  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

In [5]:
df_fin= df[df['Dept']=='Finance']
df_fin

        ID   Name     Dept    Salary        Date
1   EMP002    Bob  Finance  117969.0  2018-06-06
3   EMP004  David  Finance       NaN  2019-04-15
4   EMP005    Eva  Finance   78693.0  2019-09-18
9   EMP010   Jack  Finance  109150.0  2021-11-08
12  EMP013  Molly  Finance  117435.0  2023-02-21

In [6]:
med = df_fin['Salary'].median()
med

113292.5

In [7]:
df['Salary']=df['Salary'].fillna(med)
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance  113292.5  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah          NaN   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

Data Cleaning - Replacing NaN department by 'Marketing'

In [12]:
df.iloc[7,2] = 'Marketing'
df

        ID     Name         Dept    Salary        Date
0   EMP001    Alice        Sales  114925.0  2018-01-01
1   EMP002      Bob      Finance  117969.0  2018-06-06
2   EMP003  Charlie    Marketing   55311.0  2018-11-09
3   EMP004    David      Finance  113292.5  2019-04-15
4   EMP005      Eva      Finance   78693.0  2019-09-18
5   EMP006    Frank  Engineering  121932.0  2020-02-22
6   EMP007    Grace    Marketing   75658.0  2020-07-27
7   EMP008   Hannah    Marketing   68431.0  2020-12-31
8   EMP009     Ivan    Marketing   52747.0  2021-06-05
9   EMP010     Jack      Finance  109150.0  2021-11-08
10  EMP011    Kevin        Sales  115725.0  2022-04-14
11  EMP012    Laura    Marketing   85773.0  2022-09-17
12  EMP013    Molly      Finance  117435.0  2023-02-21
13  EMP014   Nathan  Engineering  106886.0  2023-07-27
14  EMP015   Oliver        Sales  116803.0  2023-12-31

Filtering: Filter the DataFrame to show only employees who earn more than 100,000 and work in "Sales" or "Engineering".

In [23]:
(df['Salary']>100000)

0      True
1      True
2     False
3      True
4     False
5      True
6     False
7     False
8     False
9      True
10     True
11    False
12     True
13     True
14     True
Name: Salary, dtype: bool

In [21]:
df['Dept'].isin(['Sales','Engineering'])

0      True
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14     True
Name: Dept, dtype: bool

In [ ]:
df[(df['Salary']>100000) & (df['Dept'].isin(['Sales','Engineering']))].sort_values(['Dept','Name'])

        ID    Name         Dept    Salary        Date
0   EMP001   Alice        Sales  114925.0  2018-01-01
5   EMP006   Frank  Engineering  121932.0  2020-02-22
10  EMP011   Kevin        Sales  115725.0  2022-04-14
13  EMP014  Nathan  Engineering  106886.0  2023-07-27
14  EMP015  Oliver        Sales  116803.0  2023-12-31

Aggregation: Calculate the average salary and total employee count for each unique department.

In [48]:
df_x=df.groupby('Dept')
df_x['Salary'].mean()

Dept
Engineering    114409.000000
Finance        107307.900000
Marketing       67584.000000
Sales          115817.666667
Name: Salary, dtype: float64

In [49]:
df_x['ID'].count()

Dept
Engineering    2
Finance        5
Marketing      5
Sales          3
Name: ID, dtype: int64

In [53]:
df_result = pd.DataFrame({
    'Avg Salary':df_x['Salary'].mean(),
    'count':df_x['ID'].count()
})

df_result

                Avg Salary  count
Dept
Engineering  114409.000000      2
Finance      107307.900000      5
Marketing     67584.000000      5
Sales        115817.666667      3

Datetime Handling: Convert the Join_Date column to actual datetime objects and filter out anyone who joined after January 1st, 2021.

In [67]:
df[df['Date']>='2021-01-01'].sort_values('Date',ascending=False)

        ID    Name         Dept    Salary        Date
14  EMP015  Oliver        Sales  116803.0  2023-12-31
13  EMP014  Nathan  Engineering  106886.0  2023-07-27
12  EMP013   Molly      Finance  117435.0  2023-02-21
11  EMP012   Laura    Marketing   85773.0  2022-09-17
10  EMP011   Kevin        Sales  115725.0  2022-04-14
9   EMP010    Jack      Finance  109150.0  2021-11-08
8   EMP009    Ivan    Marketing   52747.0  2021-06-05

Feature Engineering: Create a new column named Years_of_Service based on how many years they have been at the company relative to today.

In [75]:
today = pd.to_datetime('today')

In [79]:
df['Date']=pd.to_datetime(df['Date'])

In [99]:
df['Years_of_Service'] = ((today - df['Date']).dt.days//365)
df

        ID     Name         Dept    Salary       Date  Years_of_Service
0   EMP001    Alice        Sales  114925.0 2018-01-01                 8
1   EMP002      Bob      Finance  117969.0 2018-06-06                 8
2   EMP003  Charlie    Marketing   55311.0 2018-11-09                 7
3   EMP004    David      Finance  113292.5 2019-04-15                 7
4   EMP005      Eva      Finance   78693.0 2019-09-18                 6
5   EMP006    Frank  Engineering  121932.0 2020-02-22                 6
6   EMP007    Grace    Marketing   75658.0 2020-07-27                 5
7   EMP008   Hannah    Marketing   68431.0 2020-12-31                 5
8   EMP009     Ivan    Marketing   52747.0 2021-06-05                 5
9   EMP010     Jack      Finance  109150.0 2021-11-08                 4
10  EMP011    Kevin        Sales  115725.0 2022-04-14                 4
11  EMP012    Laura    Marketing   85773.0 2022-09-17                 3
12  EMP013    Molly      Finance  117435.0 2023-02-21                 3
13  EMP014   Nathan  Engineering  106886.0 2023-07-27                 2
14  EMP015   Oliver        Sales  116803.0 2023-12-31                 2