Assignment - Duplicate data removal

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('course_data.csv')
data

    Sr. No                           Course       Domain  Duration
0        1           Full Stack Development         Java  6 Months
1        2           Full Stack Development       Python  6 Months
2        3                  Ethical Hacking      General  3 Months
3        4           Full Stack Development      Dot Net  6 Months
4        5           Full Stack Development   MEAN Stack  6 Months
5        6           Full Stack Development   MERN Stack  6 Months
6        7  Data Science & Machine Learning       Python  6 Months
7        8                   Data Analytics       Python  4 Months
8        9                  Web Development  HTML/CSS/JS  3 Months
9       10          Android App Development       Kotlin  3 Months
10      11              iOS App Development        Swift  3 Months
11      11              iOS App Development        Swift  3 Months
12      12                  Cloud Computing          AWS  3 Months
13      13                           DevOps        Tools  3 Months
14      14                    Cybersecurity      General  3 Months
15      15                     UI/UX Design        Figma  2 Months
16      16                Digital Marketing      General  2 Months
17      17          Artificial Intelligence       Python  4 Months
18      18           Full Stack Development          PHP  6 Months
19      18           Full Stack Development          PHP  6 Months
20      18           Full Stack Development          PHP  6 Months

In [4]:
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20     True
dtype: bool

In [6]:
dup_df = data[data.duplicated()]
dup_df

    Sr. No                  Course Domain  Duration
11      11     iOS App Development  Swift  3 Months
19      18  Full Stack Development    PHP  6 Months
20      18  Full Stack Development    PHP  6 Months

In [9]:
data.drop_duplicates(inplace=True)
data

    Sr. No                           Course       Domain  Duration
0        1           Full Stack Development         Java  6 Months
1        2           Full Stack Development       Python  6 Months
2        3                  Ethical Hacking      General  3 Months
3        4           Full Stack Development      Dot Net  6 Months
4        5           Full Stack Development   MEAN Stack  6 Months
5        6           Full Stack Development   MERN Stack  6 Months
6        7  Data Science & Machine Learning       Python  6 Months
7        8                   Data Analytics       Python  4 Months
8        9                  Web Development  HTML/CSS/JS  3 Months
9       10          Android App Development       Kotlin  3 Months
10      11              iOS App Development        Swift  3 Months
12      12                  Cloud Computing          AWS  3 Months
13      13                           DevOps        Tools  3 Months
14      14                    Cybersecurity      General  3 Months
15      15                     UI/UX Design        Figma  2 Months
16      16                Digital Marketing      General  2 Months
17      17          Artificial Intelligence       Python  4 Months
18      18           Full Stack Development          PHP  6 Months